### ISSUE TITLE
Environment variable that Environment defines gets overridden by DEFAULTS

### ISSUE THREAD

**Issue by VassilisVassiliadis** [st4sd/st4sd-runtime-core#3]
**Issue**: 

As a Virtual Experiment developer, I expect that components with the below `environment` receive an environment variable `FORCEFIELD_DIR` whose value is `/foo/first/forcefield`.

```yaml
environments:
  my-platform:
    my-env:
      DEFAULTS: BASE_DIR:PATH:LD_LIBRARY_PATH
      BASE_DIR: /foo/bar
      FORCEFIELD_DIR: ${BASE_DIR}/forcefield
```

I observe that this is not the case if I add `BASE_DIR` in the `DEFAULTS` option. 
Instead, I notice that `FORCEFIELD_DIR` is set to `/forcefield`.

This implies that the mechanism which fills in the `DEFAULTS` completely overrides the information inside the environment definition.

**Solution**: 

We want to be able to support scenarios such as:

```yaml
my-env:
  DEFAULTS: PATH
  PATH: /my/awesome/dir/:${PATH}
```

Therefore:
1. we should maintain a dictionary of `default` values
2. populate it with values from `DEFAULTS` (using os.environ.get($key, "")`
3. IF the environment defines `$key` too, then 
   1. expand the value of `$key` to replace references to `$key` using `defaults[key]`
   2. set `defaults[key]` to `environment[key]`
4. Use `defaults[key]` to replace reference of `$key` in any `environment[x]` to `defaults[key]`

**Acceptance Criteria**

- [x] `FORCEFIELD_DIR` above receives the value `/foo/bar/forcefield`
