### ISSUE TITLE
 Implement minimal docker backend for st4sd-runtime-core

### ISSUE THREAD

**Issue by VassilisVassiliadis** [st4sd/st4sd-runtime-core#31]
# Feature request

## Story
As a virtual experiment developer I would like to use a docker backend to test out my virtual experiments on my laptop before I use my Kubernetes environment.

Proposed changes to the backend specification:

```yaml
resourceManager:
  config:
    backend: docker
  docker:
    # my image here
    image: quay.io/st4sd/st4sd-runtime-core:platform-release-latest
```

Done When: 
- [x] a minimalistic Docker backend invokes the `docker run` command
- [x] the docker backend has a `resourceManager.docker.image` field
