### ISSUE TITLE
[BUG] invalid environment defintion if the chosen platform does not define the environment but inherits it from the default platform

### ISSUE THREAD

**Issue by VassilisVassiliadis** [st4sd/st4sd-runtime-core#43]
**Issue**

When a component does not specify an environment, we have it use the `environment` environment. This is a special environment which if it doesn't exist, we auto-populate using the env-vars of the shell that is running the `elaunch.py` process (i.e. the runtime entrypoint).

When the experiment instance uses a platform which does not explicitly specify the `environment` environment the code does not check the `default` platform. It ends up auto-generating the contents of the `environment` environment. This is prolematic because the component may receive completely wrong environment variables. For example, if running on k8s or with docker the component may not even be able to check its executable.

Similarly, if the "active" platform contains the environment but the `default` platform doesn't, the code mistakenly considers that the experiment is missing the definition of the environment.

Example flowir which reproduces the 1st issue:

```yaml
environments:
  default:
      environment:
        DEFAULTS: PATH:LD_LIBRARY_PATH
        PATH: hello:$PATH
        LD_LIBRARY_PATH: $LD_LIBRARY_PATH
platforms:
- default
- empty

components:
- stage: 0
  name: hello
  command:
    executable: sh
    arguments: -c "if [[ \"${PATH}\" =~ ^hello ]]; then
        echo Correct;
      else
        echo Wrong;
        exit 1;
      fi"
    environment: "environment"
    expandArguments: none
```

**Done when**
- [x] st4sd correctly applies the layering of environments when the selected platform does not define an environment but the default one does
- [x] we have a unit test for the above FlowIR which checks that `${PATH}` starts with `hello:` for both platforms `default` and `empty`
- [x] run the `band-gap-pm3-gamess-us` experiment for SMILES C and register it in the datastore (this check verifies that the changes in st4sd-runtime-core do not break something in the datastore or the runtime-service)
